### ISSUE TITLE
Style is not defind

### ISSUE THREAD

**Issue by TherealONE12** [CPScript/Kitty-Tools#64]
**Describe the bug**
When triing to run (Linux) this error comes:

/downloads/Kitty-Tools $ python main.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pip", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 77, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 15, in <module>
    from pip._internal.cli.req_command import (
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 21, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/index/package_finder.py", line 30, in <module>
    from pip._internal.req import InstallRequirement
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/req/__init__.py", line 8, in <module>
    from .req_install import InstallRequirement
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 40, in <module>
    from pip._internal.operations.install.wheel import install_wheel
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distlib/scripts.py", line 16, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/distlib/compat.py", line 81, in <module>
    import xmlrpc.client as xmlrpclib
  File "/data/data/com.termux/files/usr/lib/python3.11/xmlrpc/client.py", line 138, in <module>
    from xml.parsers import expat
  File "/data/data/com.termux/files/usr/lib/python3.11/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: dlopen failed: library "libexpat.so.1" not found
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/Kitty-Tools/main.py", line 1, in <module>
    from scripts.sprint import sprint
  File "/data/data/com.termux/files/home/downloads/Kitty-Tools/scripts/sprint.py", line 3, in <module>
    from scripts import colors
  File "/data/data/com.termux/files/home/downloads/Kitty-Tools/scripts/colors.py", line 10, in <module>
    all_col= [Style.BRIGHT+Fore.RED,Style.BRIGHT+Fore.CYAN,Style.BRIGHT+Fore.LIGHTCYAN_EX, Style.BRIGHT+Fore.LIGHTBLUE_EX, Style.BRIGHT+Fore.LIGHTCYAN_EX,Style.BRIGHT+Fore.LIGHTMAGENTA_EX,Style.BRIGHT+Fore.LIGHTYELLOW_EX]
              ^^^^^
NameError: name 'Style' is not defined. Did you mean: 'type'?
~/downloads/Kitty-Tools

**To Reproduce**
 - Try to run it via the Linux commands in readme.md on Termux

**Desktop (please complete the following information):**
 - OS: Androide
 - Browser DuckDuckGo
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J6 Rooted
 - OS: Androide 10
 - Browser DuckDuckGo
 - version: Latest

**Comment by CPScript** [comment]
I just made a LITE version for this reason, please cheak it out as it might help (its still in development and might not work) https://github.com/CPScript/Kitty-Tools/tree/main/LITE
